# Generated by Django 3.1.7 on 2021-03-22 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accntType', models.CharField(help_text='The type of Account: User, Owner, or Manager', max_length=10)),
                ('name', models.CharField(help_text='Name of the user', max_length=40)),
                ('email', models.EmailField(help_text='Email of the user', max_length=254)),
                ('password', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.UUID('01c4e0fe-1907-44e4-8d40-245bcecce46c'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False)),
                ('accntInfo', models.JSONField()),
            ],
            options={
                'ordering': ['email', 'accntType', 'name'],
            },
        ),
    ]
