# Generated by Django 3.1.7 on 2021-04-06 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The long name of the event, with spaces', max_length=50)),
                ('shortName', models.CharField(help_text="Short event name, used when creating attendant 'email' addresses", max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('address', models.CharField(help_text='Address of the Event', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the parking lot', max_length=20)),
                ('address', models.CharField(help_text='Address of the parking lot', max_length=100)),
                ('parking', models.IntegerField(help_text='Number of available normal parking spaces')),
                ('tailgate', models.IntegerField(help_text='Number of available tailgate parking spaces')),
                ('date', models.DateField(help_text='Date of the Event')),
                ('price', models.DecimalField(decimal_places=2, default=20.0, help_text='Cost of a normal parking spot', max_digits=5)),
                ('tailgatePrice', models.DecimalField(decimal_places=2, default=30.0, help_text='Cost of a tailgate parking spot', max_digits=5)),
                ('event', models.ManyToManyField(help_text='Event(s) that will use this parking lot', to='parkingGenie.Event')),
            ],
            options={
                'ordering': ['date', 'price', 'tailgatePrice'],
            },
        ),
    ]
