# Generated by Django 3.1.7 on 2021-03-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accntInfo',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='The users password', max_length=15),
        ),
    ]
