# Generated by Django 3.1.7 on 2021-03-22 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0002_auto_20210321_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd32bccd-89f7-4cac-9e88-1b062da6c441'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False),
        ),
    ]
