# Generated by Django 3.1.7 on 2021-04-03 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0003_auto_20210401_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebef9695-d7a3-482c-9878-d22522feef3e'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False),
        ),
    ]
