# Generated by Django 3.1.7 on 2021-04-06 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0004_auto_20210322_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0867b5e-d2fc-4c78-8ea8-9e3e9be964a4'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False),
        ),
    ]
