# Generated by Django 3.1.7 on 2021-04-04 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0004_auto_20210402_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ce0146f-0510-4845-a68d-d5f3183e91d7'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False),
        ),
    ]
