# Generated by Django 3.1.7 on 2021-03-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0005_auto_20210323_2122'),
        ('parkingGenie', '0005_auto_20210324_1722'),
    ]

    operations = [
    ]
