# Generated by Django 3.1.7 on 2021-04-04 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0005_auto_20210404_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4bc8aeb-1703-4456-a3bc-f9fca355c671'), help_text='Unique ID for this particular Account', primary_key=True, serialize=False),
        ),
    ]
