# Generated by Django 3.1.7 on 2021-04-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0006_auto_20210406_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='userType',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
