# Generated by Django 3.1.7 on 2021-03-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0007_auto_20210330_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='parkingLot',
            field=models.ForeignKey(help_text='Parking Lot to which this attendant is assigned', null=True, on_delete=django.db.models.deletion.RESTRICT, to='parkingGenie.parkinglot'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='owner',
            field=models.ForeignKey(help_text='Owner of above parking lot', on_delete=django.db.models.deletion.RESTRICT, to='parkingGenie.owner'),
        ),
    ]
