# Generated by Django 3.1.7 on 2021-03-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingGenie', '0008_auto_20210330_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'ordering': ['date', 'price', 'tailgatePrice']},
        ),
    ]
